# Generated by Django 5.2.4 on 2025-09-01 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='users/')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('bio', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('databio', models.CharField(max_length=200)),
            ],
        ),
    ]
