# Generated by Django 5.2.4 on 2025-09-01 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fronend', '0002_remove_user_bio_remove_user_databio_remove_user_img_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Odam',
        ),
    ]
