# Generated by Django 5.2.4 on 2025-09-01 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fronend', '0003_rename_user_odam'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='users/')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('username', models.CharField(max_length=200)),
                ('databio', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Odam',
        ),
    ]
