# Generated by Django 5.2.4 on 2025-09-01 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fronend', '0004_user_delete_odam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yosh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
