# Generated by Django 5.2.4 on 2025-09-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fronend', '0005_yosh_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='yosh',
            name='ism1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
