# Generated by Django 5.2.4 on 2025-09-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fronend', '0006_yosh_ism1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('yosh', models.IntegerField()),
                ('kurs', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Yosh',
        ),
    ]
