# Generated by Django 5.2.4 on 2025-09-01 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fronend', '0007_student_delete_yosh'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
