# Generated by Django 5.2.4 on 2025-09-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fronend', '0009_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='ism',
            new_name='bio',
        ),
        migrations.RemoveField(
            model_name='student',
            name='kurs',
        ),
        migrations.RemoveField(
            model_name='student',
            name='yosh',
        ),
        migrations.AddField(
            model_name='student',
            name='birthday',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='img',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
