# Generated by Django 5.2.4 on 2025-09-01 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fronend', '0010_rename_ism_student_bio_remove_student_kurs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='img',
        ),
    ]
