# Generated by Django 5.2.4 on 2025-09-01 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fronend', '0011_remove_student_img'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='User',
        ),
    ]
