# Generated by Django 5.2.4 on 2025-09-01 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fronend', '0012_rename_student_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Odam',
        ),
    ]
