# Generated by Django 5.2.4 on 2025-09-02 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fronend', '0013_rename_user_odam'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Odam',
        ),
    ]
