# Generated by Django 5.2.4 on 2025-09-01 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
